<?xml version="1.0" encoding="utf-8"?><Database Name="WarungPintar" Class="WarungPintarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=WarungPintar;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="HelloWebAPI.Properties.Settings" SettingsPropertyName="WarungPintarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Kepada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>